### ISSUE TITLE
is:issue is:open 大佬请问 有详细的使用文档吗？有项目列子吗？

### ISSUE THREAD

**Issue by sukai33** [chennian32/web_display#1]
is:issue is:open 大佬请问 有详细的使用文档吗？有项目列子吗？

**Comment by chennian32** [comment]
参考：绘制节点流程图：【Html5Cancas绘制Nodeflow流程图】 https://www.bilibili.com/video/BV1GB4y1V76s/?share_source=copy_web&vd_source=27dc819a6f36a754fd498fff750cbac4
参考：绘制ROI和显示区域：【Html5Canvas实现显示区域和绘制ROI】 https://www.bilibili.com/video/BV1GS4y1W7rT/?share_source=copy_web&vd_source=27dc819a6f36a754fd498fff750cbac4
